name: Build and push images
on:
  push:
    branches:
    - master
    paths:
    - "*"
    - "!README.md"
    - "!build.rb"
  schedule:
    # As well as running when we make changes we should run at least
    # every week in order to pick up new parent images and new versions
    - cron:  "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: "1"
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        add_git_labels: true
        repository: the-mog/hello-node
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}